config/routes.rb
Rails.application.routes.draw do
  resources :schedule_items
  resources :schedules
  resources :customers
  resources :professionals
  resources :products
  resources :companies

end

app/models/schedule_item.rb
class ScheduleItem < ActiveRecord::Base
  belongs_to :schedule
  has_many :product
end

app/controllers/schedule_items_controller.rb
class ScheduleItemsController < ApplicationController
  before_action :set_schedule_item, only: [:show, :edit, :update, :destroy]

  # GET /schedule_items
  # GET /schedule_items.json
  def index
    @schedule_items = ScheduleItem.all
  end

  # GET /schedule_items/1
  # GET /schedule_items/1.json
  def show
  end

  # GET /schedule_items/new
  def new
    @schedule_item = ScheduleItem.new
  end

  # GET /schedule_items/1/edit
  def edit
  end

  # POST /schedule_items
  # POST /schedule_items.json
  def create
    @schedule_item = ScheduleItem.new(schedule_item_params)

    respond_to do |format|
      if @schedule_item.save
        format.html { redirect_to @schedule_item, notice: 'Schedule item was successfully created.' }
        format.json { render :show, status: :created, location: @schedule_item }
      else
        format.html { render :new }
        format.json { render json: @schedule_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedule_items/1
  # PATCH/PUT /schedule_items/1.json
  def update
    respond_to do |format|
      if @schedule_item.update(schedule_item_params)
        format.html { redirect_to @schedule_item, notice: 'Schedule item was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule_item }
      else
        format.html { render :edit }
        format.json { render json: @schedule_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedule_items/1
  # DELETE /schedule_items/1.json
  def destroy
    @schedule_item.destroy
    respond_to do |format|
      format.html { redirect_to schedule_items_url, notice: 'Schedule item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule_item
      @schedule_item = ScheduleItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_item_params
      params.require(:schedule_item).permit(:price, :schedule_id, :product_id)
    end
end

app/helpers/schedule_items_helper.rb
module ScheduleItemsHelper
end

app/views/schedule_items/_form.html.erb
<%= form_for(@schedule_item) do |f| %>
  <% if @schedule_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule_item.errors.count, "error") %> prohibited this schedule_item from being saved:</h2>

      <ul>
      <% @schedule_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :schedule_id %><br>
    <%= f.text_field :schedule_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedule_items/edit.html.erb
<h1>Editing Schedule Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule_item %> |
<%= link_to 'Back', schedule_items_path %>

app/views/schedule_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schedule Items</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Schedule</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedule_items.each do |schedule_item| %>
      <tr>
        <td><%= schedule_item.price %></td>
        <td><%= schedule_item.schedule %></td>
        <td><%= schedule_item.product %></td>
        <td><%= link_to 'Show', schedule_item %></td>
        <td><%= link_to 'Edit', edit_schedule_item_path(schedule_item) %></td>
        <td><%= link_to 'Destroy', schedule_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule item', new_schedule_item_path %>

app/views/schedule_items/new.html.erb
<h1>New Schedule Item</h1>

<%= render 'form' %>

<%= link_to 'Back', schedule_items_path %>

app/views/schedule_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @schedule_item.price %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @schedule_item.schedule %>
</p>

<p>
  <strong>Product:</strong>
  <%= @schedule_item.product %>
</p>

<%= link_to 'Edit', edit_schedule_item_path(@schedule_item) %> |
<%= link_to 'Back', schedule_items_path %>